### ISSUE TITLE
RSRP Meter

### ISSUE THREAD

**Issue by davidbtc2009** [christianrowlands/android-network-survey#16]
What is the upper and lower bounds of your RSRP meter? I know i have done data sessions at -115dbm and calling works (somewhat) all the way down at -125dbm though a text would be better at that level. Anything from -90 up to -70 ought to be considered a perfect connection.

**Comment by christianrowlands** [comment]
Great question, I think I need to find a way to include that information in the UI. Maybe when it is clicked.

The minimum LTE RSRP value that can represented by the meter bar is -125, and the maximum is -90. Of course, as you mention, you can have better values, than -90, but I took the same approach you did and anything better than -90 is "great".

Posting the other protocols here incase anyone else is interested:

GSM:  
- Min: -107
- Max: -89

UMTS:
- Min: -107
- Max: -77

LTE:
- Min: -125
- Max: -90

NR:
- Min: -110
- Max: -70

Of course the 3GPP spec defined ranges are different, but I am not looking to represent those ranges, I am looking to represent what is "good" or "bad" to someone using a phone.

FWIW, here is the code that represents the min and max values: https://github.com/christianrowlands/android-network-survey/blob/3660fed5c18fdfe832adef0922c7a631d81d7e8d/networksurvey/src/main/java/com/craxiom/networksurvey/model/CellularProtocol.java

Also, I still plan on working on the LTE band number request you made, I just have not gotten around to it yet as I have been focusing on another project I have. I plan on giving some attention to Network survey this month.

**Comment by davidbtc2009** [comment]
No problem and no wonder, i lock my phone to NR at all times and only drop it to LTE when i need to make a call. Are you planning to add the band numbers to NR as well? And the data session i did was at -115dbm on NR. The phone call i mentioned was -125 LTE.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by christianrowlands** [comment]
Yep, I plan on adding the band numbers for NR as well.

-115 for NR is getting pretty low! Crazy. I think I have seen -130 for an LTE call, but I might be mistaken on that as it was a while back.

**Comment by davidbtc2009** [comment]
No way would i trust a call that weak. -120 is my cutoff where i stop attempting calls and either try ott messaging (signal, matrix, email) or sms/mms texts. Nothing bandwidth intensive or real-time. Because if the signal fluctuates much from changing position, blocking an antenna, etc its likely to fail.

Sent from Proton Mail mobile

-------- Original Message --------
