### ISSUE TITLE
Several proprietary libraries were added with v1.9.0

### ISSUE THREAD

**Issue by IzzySoft** [christianrowlands/android-network-survey#17]
The latest release seems to have added several non-free libraries:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Google Ads (/com/google/ads): Ads,NonFreeDep
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Cloud Audit Logs (/com/google/cloud/audit): Tracking
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

8 offenders.
```

The last version before that only had the "Cloud Audit Logs". As the changelogs don't say: Did the other ones slip in by accident (e.g. by updating dependencies) and will be removed with the next release – or was that intentionally (which would mean I'll have to remove your app from my repo again)? For now I've just removed v1.9.0 again and disabled updates.

**Comment by christianrowlands** [comment]
I did add these libraries on purpose. I did so to track the usage of a feature. I figured this was the easiest approach. Go ahead and remove the app from your repo and if I can figure out another way to solve the problem I ran into I will reach back out and let you know that the apk is clean again.

Sorry for the trouble. I should have hit you up about the change.

**Comment by IzzySoft** [comment]
Happens. But though those libs might have been the easiest approach, they are not the best solution privacy-wise. You might wish to check with my snippet for alternatives [here](https://gitlab.com/-/snippets/1896503#acceptable-analytics), maybe there's something suitable. I'll meanwhile leave updates disabled (still hoping for a solution in the near™ future) and put a note in my config. Looking forward to good news then – and keep my :crossed_fingers: for an easy *and privacy-friendly* solution to be implemented without too much trouble!

**Comment by christianrowlands** [comment]
Yeah, good points. I will see what I can do. I will leave this issue open while I do some research.

**Comment by christianrowlands** [comment]
Ok, check 1.10.0 over. I was able to rip out the firebase libraries.

**Comment by IzzySoft** [comment]
Thanks, that worked out fine! Only one left now:

```
Offending libs:
---------------
* Cloud Audit Logs (/com/google/cloud/audit): Tracking

1 offenders.
```

Added this one manually and re-enabled auto-updates. Thanks a lot again!
