### ISSUE TITLE
Landscape mode 

### ISSUE THREAD

**Issue by xmha97** [christianrowlands/android-network-survey#19]
Hi, thanks for this app.
Please support the landscape mode.

**Comment by christianrowlands** [comment]
I will look into supporting landscape mode. I have not added it to date because of the problem of managing the state when a rotation occurs, but maybe I can get something working.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by christianrowlands** [comment]
I know this is a really old request, but I added landscape mode to Network Survey. The feature will be released with the next version of NS, which I plan on doing after I add CSV logging support and do some testing. Assuming the testing goes well, I will release it at the end of next week or the following week.

Thanks for the request and hopefully I can pump out features faster next time. 

Cheers! 🥃
