### ISSUE TITLE
Cellular Refresh Frequency

### ISSUE THREAD

**Issue by Juderer** [christianrowlands/android-network-survey#21]
Hi, I'm building an application to show cellular information (LTE or NR service and neighbor cells). There is a huge confusion that my programming refresh less frequently than yours. Would you guys give me some advice or reference? THANKs a lot!!!

**Comment by christianrowlands** [comment]
How are you getting the information for LTE and NR cells? 

In Network Survey the term "scanning" is a bit of a misnomer. Really all I am doing is making a call to `TelephonyManager#requestCellInfoUpdate` at a set interval. You can see [that call here](https://github.com/christianrowlands/android-network-survey/blob/develop/networksurvey/src/main/java/com/craxiom/networksurvey/services/NetworkSurveyService.java#L1448). And a [few lines down](https://github.com/christianrowlands/android-network-survey/blob/develop/networksurvey/src/main/java/com/craxiom/networksurvey/services/NetworkSurveyService.java#L1464) you can see where I schedule the next run of that handler using the user preference scan rate.

Let me know if you have any questions.

**Comment by Juderer** [comment]
@christianrowlands Thank you very much!
