### ISSUE TITLE
[Feature Request] add dual sim support and show carrier aggregation.

### ISSUE THREAD

**Issue by saswatasarkar13** [christianrowlands/android-network-survey#25]
Hi, Please add dual sim support. It just shows the data sim. And also the name doesn't change.

I have seen it shows associated signals in the LTE neighbors. But it would be better if you show, like, 2CA or 3CA.

Nice app btw. Your app gives me hope as I might be able to uninstall Netmonstar some day.

Thank you very much for making this.

**Comment by christianrowlands** [comment]
Hey @saswatasarkar13 . Thank you for the feature request. I had not considered dual SIM support. I looked at the code and there is a way to get it, but it is strangely a lot of work, but I will see if I can code something up to map the cell information to the sim it came from.

You mention wanting to uninstall NetMonster. I am curious what you don't like about that app. In other words, what else can I add to Network Survey that would help improve it?

**Comment by saswatasarkar13** [comment]
Hi, Sorry for the late reply, and Thank you for considering the feature. If you can do it that would be a great feature for the dual sim users. And also, please consider, carrier aggregation as well. Like 2CA and 2300mhz+2300mhz.

Firstly, it is based on an Apache 2.0 licensed code “NetMonster Core”, but the app is proprietary and not available on f-droid. 
the features you could add are like, 

1. it shows graph of signal strength and time and some other data with time graphs.
2. It shows neighbor cell towers with there location and the phone's location. With a mark on the cell tower the phone is associated with (multiple for carrier aggregation)
and lot more.....
So, you can probably install and check the software out yourself.
And also a documentation about what all the terms mean like MOC, MNC, TAC, CID means would be a great help for a person like me who does not know or does not have a background in electronic or telecommunication…

**Comment by christianrowlands** [comment]
@saswatasarkar13 Just to give you an update, I am pretty far along with adding support for Dual SIMs. I have it all coded up but I need to run it through the paces for testing. But it is coming together nicely. Thanks for the suggestion.

As for carrier aggregation support, I have not dug into that yet. I need to do some research on the Android APIs to figure out how they work with CA.

For your bullets on other features...

1. I like the idea of including a graph to show a short history of signal values. I will start looking into that soon.
2. For the location of the serving cell and neighbor towers, I wonder how NetMonster gets that. There are two ways that I can think of. First, it could calculate it as you drive around using the signal strength. This approach would be highly inaccurate if you don't have a ton of survey data and I am not sure I want to do that. Even with a lot of data it can be inaccurate. The second option is to use one of the publicly available databases of cell tower locations. I think that might be an option as long as there is a free one. I guess a third option is to start building my own database of survey data to try and calculate cell tower locations.
3. Including descriptions for the terms is a great idea, and pretty simple to do. I will see if I can knock that out.

**Comment by christianrowlands** [comment]
@saswatasarkar13 , Version 1.16 has been released and it adds support for Dual SIMs. Let me know if you run into any problems, and I have written down your other feedback and will keep working towards it. Thanks for the suggestion and using the app!
