### ISSUE TITLE
[Feature Request] MQTT Topic Customization

### ISSUE THREAD

**Issue by mrepste** [christianrowlands/android-network-survey#26]
Requesting a feature in the MQTT settings (and associated QR-code-based configuration) that would allow a user to prepend the NetworkSurvey MQTT topics with a provided string. For instance, if the user provides the string `network_survey/`, then the published topics become:

- `network_survey/gsm_message`
- `network_survey/cdma_message`
- ...etc.

This would be useful for a few reasons:

- **Organization** -- right now, the topics come in at the root of the MQTT broker. Without any identifying information relative to NetworkSurvey, it is not immediately obvious what the source of these topics is especially when the MQTT broker is used for data other than NetworkSurvey
- **Security** -- right now, it is hard to configure an MQTT broker ACL without specifying all of the NetworkSurvey topics manually. My current configuration allows NetworkSurvey devices to publish _only_ to NetworkSurvey API topics. If/when new topics are added in the future, the configuration needs to be manually updated. Being able to partition the NetworkSurvey messages into a "category" would allow use of MQTT hierarchy wildcard patterns and improve forward compatibility.

**Comment by christianrowlands** [comment]
Yeah, this makes sense and is a great feature request.

I am wondering if the MQTT topic prefix should be set in the MQTT UI, or in the app settings. I could see an argument for both. If I place it in the app settings, then I would probably display something in the MQTT UI about the topic prefix if it is set, and maybe even provide a direct link to the settings so the user can easily change it.

What are your thoughts?

**Comment by mrepste** [comment]
I'd lean more towards keeping it within the MQTT configuration dialog, if only because it's such an MQTT-specific setting. If future versions of NetworkSurvey end up integrating other pub/sub-type protocols, the generalized app settings might get littered with all variations?

**Comment by christianrowlands** [comment]
Yeah, I think you are right. Keeping it with the MQTT settings will make it more obvious. I will see what I can work up.

**Comment by christianrowlands** [comment]
This feature was released in version 1.17! @mrepste , let me know if it does not meet your expectations.
