### ISSUE TITLE
NR bandwidth

### ISSUE THREAD

**Issue by shortwavesurfer2009** [christianrowlands/android-network-survey#28]
The LTE has a bandwidth section and i was wondering if NR could have it too.

Also, whats with the "," after the band numbers?

**Comment by christianrowlands** [comment]
Unfortunately, the Android API does not allow for access to the NR bandwidth information like it does for LTE. I am not sure why that is the case, but LTE Bandwidth support was added in Android 9 where regular LTE support was added in Android 4.2. I am not sure why it took so long to add LTE Bandwidth support in Android, but maybe NR will follow the same path. I will keep an eye out every time Android gets an update to see if NR Bandwidth is added.

As for the "," after the band numbers... Looking in the code now I see my mistake. I will fix that extra comma. Thanks for reporting it.

**Comment by christianrowlands** [comment]
Here is the commit that fixes the comma issue: https://github.com/christianrowlands/android-network-survey/commit/1a037ed84dc81924cc9b59d1cb8ea5a52b8ea0a3

**Comment by shortwavesurfer2009** [comment]
Cool, with the camma issue done are you going to leave the issue open until android gains support or go ahead and close it?

**Comment by christianrowlands** [comment]
I will close it for now. I always scroll through the cellular developer docs for every Android release, so if I see it I will add it in then.

Thanks for creating this issue.
