### ISSUE TITLE
Alternative download source?

### ISSUE THREAD

**Issue by IzzySoft** [christianrowlands/android-network-survey#3]
Great to see a network survey app that comes without any trackers! Would you consider making it available outside the walled garden of Google Play as well – for us tin-foils avoiding that place, and for those who cannot access it? Attaching the APK to its corresponding release would be a great idea.

Thanks in advance!

**Comment by christianrowlands** [comment]
Yeah, I could easily upload the APK for each release.  I am wrapping up some changes and can upload and post the APK for the next release.

I appreciate you reaching out!  Feel free to drop questions, suggestions, or ideas once you get a chance to install the app.

**Comment by IzzySoft** [comment]
Great, thanks in advance! Please drop me a note here when the APK is available. I might come up with additional questions then.

One suggestion already now: I'd pick the APK and make it available via [my F-Droid repo](https://apt.izzysoft.de/fdroid), so it's a) easier to find (a lot of people already use my repo) and b) updates will be signaled to users (my updater fetches them within 24h of your attaching an APK to a new tag). Hope that's fine with you :wink:

**Comment by christianrowlands** [comment]
Yep, I am good with you including the APK in your repo, and I will post here when I upload the APK.

How are you expecting the APK to be linked to the git tag?  Do you have a repo that I could use as an example?

**Comment by IzzySoft** [comment]
Oh, plenty – I could link hundreds of them. But I guess one suffices: https://github.com/C-D-Lewis/dashboard/releases And thanks again!

**Comment by christianrowlands** [comment]
Ok, I posted version 0.0.9!  Hopefully did it correctly.

**Comment by IzzySoft** [comment]
Perfect! Should show up [here](https://apt.izzysoft.de/fdroid/index/apk/com.craxiom.networksurvey) in about 22h (with the next sync; sorry, I didn't make it earlier, just returned from work, or it would have been in today's listing already). I've also already included it in my list of apps for [Cell Signal Monitoring & Mapping](https://android.izzysoft.de/applists/category/named/network_cellsignal#group_403) to improve its discoverability.

Thanks again for making your app available – and keeping it tracker-free!

PS: Not urgent, but an idea in case you're considering a wider use: as the app already collects cell IDs with their corresponding GPS coordinates, uploading the collection to services like [OpenCellID](https://opencellid.org/) and/or [MLS](https://location.services.mozilla.com/) might be a nice "by-product". I'm currently contributing to both using [Tower Collector](https://github.com/zamojski/TowerCollector) – and use a combined database of both for my local on-device "network location" via [UnifiedNlp](https://github.com/microg/android_packages_apps_UnifiedNlp) with the [LocalGsmNlpBackend](https://github.com/n76/Local-GSM-Backend) (i.e. having network location without GApps on my device), which I find great for privacy :wink:

**Comment by christianrowlands** [comment]
Great, and no worries.  No rush at all.

I did recently hear about OpenCellID, and have thought about adding support for contributing to it.  I will try to set aside some time for adding that feature.  I had not heard about MLS, but it looks cool.  Thanks for the tip!

**Comment by IzzySoft** [comment]
Gladly – thanks for your help!

**Comment by IzzySoft** [comment]
Christian, just wondering: My library scanner just reported it found references to Google's Cloud Auditing (`com.google.cloud.audit`) in your app? What is logged to that? I've checked your code here but couldn't find it; maybe some library was drawing that in?

**Comment by christianrowlands** [comment]
I am not using that directly, so it is probably coming from a dependency.

I ran `./gradlew networksurvey:dependencies` and it did not have any hits for `com.google.cloud.audit`. Do you have any more details on it?

**Comment by IzzySoft** [comment]
I could offer you the Smali output generated by ApkTool if that helps.

<details><summary>Smali of com.craxiom.networksurvey_15.apk</summary><pre>
./smali/android/annotation:
./smali/android/support/v4/app:
./smali/android/support/v4/graphics/drawable:
./smali/android/support/v4/media/session:
./smali/android/support/v4/os:
./smali/androidx/activity:
./smali/androidx/annotation:
./smali/androidx/appcompat/app:
./smali/androidx/appcompat/content/res:
./smali/androidx/appcompat/graphics/drawable:
./smali/androidx/appcompat/resources:
./smali/androidx/appcompat/text:
./smali/androidx/appcompat/view/menu:
./smali/androidx/appcompat/widget:
./smali/androidx/arch/core/executor:
./smali/androidx/arch/core/internal:
./smali/androidx/arch/core/util:
./smali/androidx/asynclayoutinflater/view:
./smali/androidx/cardview/widget:
./smali/androidx/collection:
./smali/androidx/constraintlayout/solver/widgets:
./smali/androidx/constraintlayout/widget:
./smali/androidx/coordinatorlayout/widget:
./smali/androidx/core/accessibilityservice:
./smali/androidx/core/app:
./smali/androidx/core/content/pm:
./smali/androidx/core/content/res:
./smali/androidx/core/database/sqlite:
./smali/androidx/core/graphics/drawable:
./smali/androidx/core/hardware/display:
./smali/androidx/core/hardware/fingerprint:
./smali/androidx/core/internal/view:
./smali/androidx/core/location:
./smali/androidx/core/math:
./smali/androidx/core/net:
./smali/androidx/core/os:
./smali/androidx/core/provider:
./smali/androidx/core/telephony/mbms:
./smali/androidx/core/text/util:
./smali/androidx/core/util:
./smali/androidx/core/view/accessibility:
./smali/androidx/core/view/animation:
./smali/androidx/core/view/inputmethod:
./smali/androidx/core/widget:
./smali/androidx/cursoradapter/widget:
./smali/androidx/customview/view:
./smali/androidx/customview/widget:
./smali/androidx/documentfile/provider:
./smali/androidx/drawerlayout/widget:
./smali/androidx/fragment/app:
./smali/androidx/interpolator/view/animation:
./smali/androidx/legacy/app:
./smali/androidx/legacy/content:
./smali/androidx/legacy/coreui:
./smali/androidx/legacy/coreutils:
./smali/androidx/legacy/v4:
./smali/androidx/legacy/widget:
./smali/androidx/lifecycle/livedata/core:
./smali/androidx/lifecycle/viewmodel/savedstate:
./smali/androidx/loader/app:
./smali/androidx/loader/content:
./smali/androidx/localbroadcastmanager/content:
./smali/androidx/media/app:
./smali/androidx/media/session:
./smali/androidx/navigation/common:
./smali/androidx/navigation/fragment:
./smali/androidx/navigation/ui:
./smali/androidx/preference/internal:
./smali/androidx/print:
./smali/androidx/recyclerview/widget:
./smali/androidx/savedstate:
./smali/androidx/slidingpanelayout/widget:
./smali/androidx/swiperefreshlayout/widget:
./smali/androidx/transition:
./smali/androidx/vectordrawable/animated:
./smali/androidx/vectordrawable/graphics/drawable:
./smali/androidx/versionedparcelable:
./smali/androidx/viewpager2/adapter:
./smali/androidx/viewpager2/widget:
./smali/androidx/viewpager/widget:
./smali/ar/com/hjg/pngj/chunks:
./smali/ar/com/hjg/pngj/pixels:
./smali_classes2/com/google/common/collect:
./smali_classes2/com/google/common/escape:
./smali_classes2/com/google/common/eventbus:
./smali_classes2/com/google/common/graph:
./smali_classes2/com/google/common/hash:
./smali_classes2/com/google/common/html:
./smali_classes2/com/google/common/io:
./smali_classes2/com/google/common/math:
./smali_classes2/com/google/common/net:
./smali_classes2/com/google/common/primitives:
./smali_classes2/com/google/common/reflect:
./smali_classes2/com/google/common/util/concurrent/internal:
./smali_classes2/com/google/common/xml:
./smali_classes2/com/google/errorprone/annotations/concurrent:
./smali_classes2/com/google/geo/type:
./smali_classes2/com/google/gson/annotations:
./smali_classes2/com/google/gson/internal/bind/util:
./smali_classes2/com/google/gson/internal/reflect:
./smali_classes2/com/google/gson/reflect:
./smali_classes2/com/google/gson/stream:
./smali_classes2/com/google/j2objc/annotations:
./smali_classes2/com/google/logging/type:
./smali_classes2/com/google/longrunning:
./smali_classes2/com/google/protobuf/compiler:
./smali_classes2/com/google/protobuf/util:
./smali_classes2/com/google/rpc:
./smali_classes2/com/google/thirdparty/publicsuffix:
./smali_classes2/com/google/type:
./smali_classes2/com/google/zxing/integration/android:
./smali_classes2/com/j256/ormlite/android/apptools/support:
./smali_classes2/com/j256/ormlite/android/compat:
./smali_classes2/com/j256/ormlite/dao:
./smali_classes2/com/j256/ormlite/db:
./smali_classes2/com/j256/ormlite/field/types:
./smali_classes2/com/j256/ormlite/logger:
./smali_classes2/com/j256/ormlite/misc:
./smali_classes2/com/j256/ormlite/stmt/mapped:
./smali_classes2/com/j256/ormlite/stmt/query:
./smali_classes2/com/j256/ormlite/support:
./smali_classes2/com/j256/ormlite/table:
./smali_classes2/com/squareup/okhttp/internal/framed:
./smali_classes2/com/squareup/okhttp/internal/http:
./smali_classes2/com/squareup/okhttp/internal/io:
./smali_classes2/com/squareup/okhttp/internal/tls:
./smali_classes2/io/grpc/android:
./smali_classes2/io/grpc/inprocess:
./smali_classes2/io/grpc/internal:
./smali_classes2/io/grpc/okhttp/internal/framed:
./smali_classes2/io/grpc/perfmark:
./smali_classes2/io/grpc/protobuf/lite:
./smali_classes2/io/grpc/stub/annotations:
./smali_classes2/io/grpc/util:
./smali_classes2/io/opencensus/common:
./smali_classes2/io/opencensus/contrib/grpc/metrics:
./smali_classes2/io/opencensus/internal:
./smali_classes2/io/opencensus/metrics/data:
./smali_classes2/io/opencensus/metrics/export:
./smali_classes2/io/opencensus/resource:
./smali_classes2/io/opencensus/stats:
./smali_classes2/io/opencensus/tags/propagation:
./smali_classes2/io/opencensus/tags/unsafe:
./smali_classes2/io/opencensus/trace/config:
./smali_classes2/io/opencensus/trace/export:
./smali_classes2/io/opencensus/trace/internal:
./smali_classes2/io/opencensus/trace/propagation:
./smali_classes2/io/opencensus/trace/samplers:
./smali_classes2/io/opencensus/trace/unsafe:
./smali_classes2/javax/annotation/concurrent:
./smali_classes2/javax/annotation/meta:
./smali_classes2/kotlin/annotation:
./smali_classes2/kotlin/collections/unsigned:
./smali_classes2/kotlin/comparisons:
./smali_classes2/kotlin/concurrent:
./smali_classes2/kotlin/contracts:
./smali_classes2/kotlin/coroutines/experimental/intrinsics:
./smali_classes2/kotlin/coroutines/experimental/jvm/internal:
./smali_classes2/kotlin/coroutines/experimental/migration:
./smali_classes2/kotlin/coroutines/intrinsics:
./smali_classes2/kotlin/coroutines/jvm/internal:
./smali_classes2/kotlin/experimental:
./smali_classes2/kotlin/internal/jdk7:
./smali_classes2/kotlin/io:
./smali_classes2/kotlin/jdk7:
./smali_classes2/kotlin/js:
./smali_classes2/kotlin/jvm/functions:
./smali_classes2/kotlin/jvm/internal/markers:
./smali_classes2/kotlin/jvm/internal/unsafe:
./smali_classes2/kotlin/math:
./smali_classes2/kotlin/native/concurrent:
./smali_classes2/kotlin/properties:
./smali_classes2/kotlin/random:
./smali_classes2/kotlin/ranges:
./smali_classes2/kotlin/reflect:
./smali_classes2/kotlin/sequences:
./smali_classes2/kotlin/system:
./smali_classes2/kotlin/text:
./smali_classes2/kotlin/time:
./smali_classes2/mil/nga/geopackage/attributes:
./smali_classes2/mil/nga/geopackage/core/contents:
./smali_classes2/mil/nga/geopackage/core/srs:
./smali_classes2/mil/nga/geopackage/db/master:
./smali_classes2/mil/nga/geopackage/db/metadata:
./smali_classes2/mil/nga/geopackage/db/table:
./smali_classes2/mil/nga/geopackage/extension/contents:
./smali_classes2/mil/nga/geopackage/extension/coverage:
./smali_classes2/mil/nga/geopackage/extension/index:
./smali_classes2/mil/nga/geopackage/extension/link:
./smali_classes2/mil/nga/geopackage/extension/properties:
./smali_classes2/mil/nga/geopackage/extension/related/dublin:
./smali_classes2/mil/nga/geopackage/extension/related/media:
./smali_classes2/mil/nga/geopackage/extension/related/simple:
./smali_classes2/mil/nga/geopackage/extension/scale:
./smali_classes2/mil/nga/geopackage/extension/style:
./smali_classes2/mil/nga/geopackage/factory:
./smali_classes2/mil/nga/geopackage/features/columns:
./smali_classes2/mil/nga/geopackage/features/index:
./smali_classes2/mil/nga/geopackage/features/user:
./smali_classes2/mil/nga/geopackage/geom:
./smali_classes2/mil/nga/geopackage/io:
./smali_classes2/mil/nga/geopackage/metadata/reference:
./smali_classes2/mil/nga/geopackage/persister:
./smali_classes2/mil/nga/geopackage/property:
./smali_classes2/mil/nga/geopackage/schema/columns:
./smali_classes2/mil/nga/geopackage/schema/constraints:
./smali_classes2/mil/nga/geopackage/style:
./smali_classes2/mil/nga/geopackage/tiles/features/custom:
./smali_classes2/mil/nga/geopackage/tiles/matrix:
./smali_classes2/mil/nga/geopackage/tiles/matrixset:
./smali_classes2/mil/nga/geopackage/tiles/overlay:
./smali_classes2/mil/nga/geopackage/tiles/retriever:
./smali_classes2/mil/nga/geopackage/tiles/user:
./smali_classes2/mil/nga/geopackage/user/custom:
./smali_classes2/mil/nga/geopackage/validate:
./smali_classes2/mil/nga/oapi/features/json:
./smali_classes2/mil/nga/sf/extended:
./smali_classes2/mil/nga/sf/geojson/jackson:
./smali_classes2/mil/nga/sf/proj:
./smali_classes2/mil/nga/sf/util/centroid:
./smali_classes2/mil/nga/sf/util/sweep:
./smali_classes2/mil/nga/sf/wkb:
./smali/com/craxiom/networksurvey/constants:
./smali/com/craxiom/networksurvey/fragments:
./smali/com/craxiom/networksurvey/lang:
./smali/com/craxiom/networksurvey/listeners:
./smali/com/craxiom/networksurvey/logging:
./smali/com/craxiom/networksurvey/messaging:
./smali/com/craxiom/networksurvey/model:
./smali/com/craxiom/networksurvey/mqtt:
./smali/com/craxiom/networksurvey/services:
./smali/com/craxiom/networksurvey/util:
./smali/com/craxiom/networksurvey/view:
./smali/com/fasterxml/jackson/annotation:
./smali/com/fasterxml/jackson/core/async:
./smali/com/fasterxml/jackson/core/base:
./smali/com/fasterxml/jackson/core/filter:
./smali/com/fasterxml/jackson/core/format:
./smali/com/fasterxml/jackson/core/io:
./smali/com/fasterxml/jackson/core/json/async:
./smali/com/fasterxml/jackson/core/sym:
./smali/com/fasterxml/jackson/core/type:
./smali/com/fasterxml/jackson/core/util:
./smali/com/fasterxml/jackson/databind/annotation:
./smali/com/fasterxml/jackson/databind/cfg:
./smali/com/fasterxml/jackson/databind/deser/impl:
./smali/com/fasterxml/jackson/databind/deser/std:
./smali/com/fasterxml/jackson/databind/exc:
./smali/com/fasterxml/jackson/databind/ext:
./smali/com/fasterxml/jackson/databind/introspect:
./smali/com/fasterxml/jackson/databind/jsonFormatVisitors:
./smali/com/fasterxml/jackson/databind/jsonschema:
./smali/com/fasterxml/jackson/databind/jsontype/impl:
./smali/com/fasterxml/jackson/databind/module:
./smali/com/fasterxml/jackson/databind/node:
./smali/com/fasterxml/jackson/databind/ser/impl:
./smali/com/fasterxml/jackson/databind/ser/std:
./smali/com/fasterxml/jackson/databind/type:
./smali/com/fasterxml/jackson/databind/util:
./smali/com/google/android/material/animation:
./smali/com/google/android/material/appbar:
./smali/com/google/android/material/badge:
./smali/com/google/android/material/behavior:
./smali/com/google/android/material/bottomappbar:
./smali/com/google/android/material/bottomnavigation:
./smali/com/google/android/material/bottomsheet:
./smali/com/google/android/material/button:
./smali/com/google/android/material/canvas:
./smali/com/google/android/material/card:
./smali/com/google/android/material/checkbox:
./smali/com/google/android/material/chip:
./smali/com/google/android/material/circularreveal/cardview:
./smali/com/google/android/material/circularreveal/coordinatorlayout:
./smali/com/google/android/material/color:
./smali/com/google/android/material/datepicker:
./smali/com/google/android/material/dialog:
./smali/com/google/android/material/drawable:
./smali/com/google/android/material/elevation:
./smali/com/google/android/material/expandable:
./smali/com/google/android/material/floatingactionbutton:
./smali/com/google/android/material/internal:
./smali/com/google/android/material/math:
./smali/com/google/android/material/navigation:
./smali/com/google/android/material/radiobutton:
./smali/com/google/android/material/resources:
./smali/com/google/android/material/ripple:
./smali/com/google/android/material/shadow:
./smali/com/google/android/material/shape:
./smali/com/google/android/material/snackbar:
./smali/com/google/android/material/stateful:
./smali/com/google/android/material/switchmaterial:
./smali/com/google/android/material/tabs:
./smali/com/google/android/material/textfield:
./smali/com/google/android/material/textview:
./smali/com/google/android/material/theme:
./smali/com/google/android/material/transformation:
./smali/com/google/api:
./smali/com/google/cloud/audit:
./smali/com/google/common/annotations:
./smali/com/google/common/base/internal:
./smali/com/google/common/cache:
./smali/mil/nga/tiff/compression:
./smali/mil/nga/tiff/io:
./smali/mil/nga/tiff/util:
./smali/okio:
./smali/org/checkerframework/checker/nullness/compatqual:
./smali/org/codehaus/mojo/animal_sniffer:
./smali/org/eclipse/paho/android/service:
./smali/org/eclipse/paho/client/mqttv3/internal/security:
./smali/org/eclipse/paho/client/mqttv3/internal/websocket:
./smali/org/eclipse/paho/client/mqttv3/internal/wire:
./smali/org/eclipse/paho/client/mqttv3/logging:
./smali/org/eclipse/paho/client/mqttv3/persist:
./smali/org/eclipse/paho/client/mqttv3/spi:
./smali/org/eclipse/paho/client/mqttv3/util:
./smali/org/intellij/lang/annotations:
./smali/org/jetbrains/annotations:
./smali/org/locationtech/proj4j/datum:
./smali/org/locationtech/proj4j/io:
./smali/org/locationtech/proj4j/parser:
./smali/org/locationtech/proj4j/proj:
./smali/org/locationtech/proj4j/units:
./smali/org/locationtech/proj4j/util:
./smali/org/sqlite/database/sqlite:</pre></details>

(Just click the arrow or the term "Smali" to expand) You find it in the 27th line from the bottom, together with other stuff from Google's common-java (`com.google.api`).

**Comment by christianrowlands** [comment]
It does not show up in the dependency tree, but when analyzing the APK using Android Studio, I was able to see that audit_log.proto is being included in the APK. I need to dig in a bit more and figure out which dependency is adding this.

**Comment by christianrowlands** [comment]
Looks like it is coming from the io.grpc:grpc-protobuf library.

https://mvnrepository.com/artifact/io.grpc/grpc-protobuf

I updated to the last gRPC lib version and they must have added it.

**Comment by IzzySoft** [comment]
Thanks for digging in! That's ugly. Is there anything that can be done about it? Maybe some options to toggle it off (so it's not included when building), or switching to an alternative library? I'm no Android dev so I don't know what this library does. Going by the name, it's Protocol Buffers (ProtoBuf), am I right? If so, [Google Protobuf](https://github.com/google/protobuf) comes to mind. Ugh, that even seems to be used by [GRPC](https://github.com/grpc/grpc-java) according to their Readme, so they add something on top of that what you seem to need. So is it some generator, like [protoc-gen-zap-java](https://github.com/LN-Zap/protoc-gen-zap-java)?

**Comment by IzzySoft** [comment]
(sorry, Github UI is broken, I cannot edit) Maybe pinning it to the previous version (that came without cloud logging) while investigating would be an option.

**Comment by christianrowlands** [comment]
Sorry for the slow response. I will look into excluding that specific audit_log.proto file when I pull in the protobuf library.

Are you able to pin it to the previous version on your side, or is that something I need to do?

**Comment by IzzySoft** [comment]
Sorry if I haven't been clear enough. I meant to stick to the previous version of the gRPC lib *in your app* until you could fix the issue. And no, I cannot do that :wink:

**Comment by christianrowlands** [comment]
@IzzySoft , I could have sworn I tried this back in 2020, but I just tried it again and was able to exclude the audit_log.proto file from the APK. I just released 1.11 yesterday, but with 1.12 the audit_log.proto file will no longer be in the APK. I just needed to add one line to the build file.

```
packagingOptions {
        exclude 'google/cloud/audit/audit_log.proto'
    }
```

**Comment by IzzySoft** [comment]
Awesome! So once that arrives, my updater should sound the Shofar and tell me I have to remove the `Tracking` AF. Be welcome to give me a ping, though – especially if the AF is still there 3 days later :wink:

And thanks a lot for the cleanup! There we always think it's just us users having to figure how to opt-out, but it's the developers as well. Some like you luckily do care – others don't even if given the "silver spoon" (told a bank IT department how to get rid of the "unused" Firebase Analytics sneaked in via FCM and did not even get a response – so I meanwhile even doubt it's "unused")…

**Comment by IzzySoft** [comment]
PS: [Oops](https://www.virustotal.com/gui/file/8ec3182d677307ef3f8150c5fea9e3be0ac1ec1bc4d6c2404413714ab8315375/detection/f-8ec3182d677307ef3f8150c5fea9e3be0ac1ec1bc4d6c2404413714ab8315375-1677594703), 1/63 – so rather a false positive; but just in case…

**Comment by christianrowlands** [comment]
Hmm, I can see the detection in the link you provided, but I am not sure how to dig in deeper to find out why it alerted on the APK. Do you have any additional details?

**Comment by IzzySoft** [comment]
Unfortunately not. My framework automatically sends APKs for scan there and downloads the results. What triggered which engine or even just what the finding means remained in the dark for me with very few exceptions. But if you look at the library scanner details on my site, your app now has 3 anti-features, so maybe there's a connection with the added libraries? My hopes are still that your next release, getting rid of cloud audit, kills the other offenders as well and all is green again (Cloud Audit will most likely be what dragged in GMS), and that scanner at VT will be happy again as well.

Just for curiosity, I've triggered a rescan at VT. Maybe that engine updated its definitions and the "false positive" is corrected already … Ha! See, a shot in the dark, but hit the mark :smiley: (results synced, your app has a green shield again). So: one down, two to go :smile:
