### ISSUE TITLE
Pixel Fold - Cellular Details not showing any Data

### ISSUE THREAD

**Issue by sudoritz** [christianrowlands/android-network-survey#32]
**Describe the bug**
Cellular Details not showing anything . Status = ON 

**To Reproduce**
Cellular Details not showing anything . Status = ON 

**Expected behavior**
The Cellular Behavior isnt showing up any stats (MQTT is working)

**Smartphone (please complete the following information):**
 - Device: Pixel Fold
 - Android Version: Android 14

**Comment by christianrowlands** [comment]
I don't have a pixel fold to try out, so I am going to be limited in my ability to debug this issue.

Do you know if any other cellular survey apps display the cellular data? For example, Cellmapper?

**Comment by christianrowlands** [comment]
@sudoritz , were you able to try any of the other cellular survey apps on your Pixel Fold? I am curious if they work.

**Comment by christianrowlands** [comment]
Can't duplicate this issue
