### ISSUE TITLE
German Carrier Telekom didn't show

### ISSUE THREAD

**Issue by Dtrieb** [christianrowlands/android-network-survey#36]
![Screenshot_20240405-234320](https://github.com/christianrowlands/android-network-survey/assets/3650284/c3ad4f34-4bb4-489e-beb1-1429e6d8c808)

As you can see on my screenshot the German Carrier "Telekom" didn't show in the carrier field.

Pixel 7 pro - Android 14

**Comment by christianrowlands** [comment]
Hey, thanks for reporting this bug. 

I have a similar problem with Mint Mobile in the US. I have a dual sim setup with Verizon and Mint Mobile, and for whatever reason Mint Mobile is always blank on my phone just like in your screenshot. I am running on a Pixel 8 Pro.

I have debugged the code on this and when I ask for the provider from Android it gives me an empty value. This seems to be an Android issue of some variety.

**Comment by Dtrieb** [comment]
Yes the other SIM card and carrier is showing right.

Maybe you can look how they make it:
https://github.com/mroczis/netmonster-core?utm_source=android_app

**Comment by christianrowlands** [comment]
Yeah I will take a look at how they do it. I wonder if they are performing a lookup using the MCC and MNC. I could probably put something like that together.

**Comment by christianrowlands** [comment]
I might have a fix for this. I found some other approaches to getting the carrier name that worked with Mint Mobile. I implemented one of them and just not committed the change. I will push out a release this week so you can take a look and see if it works on your device.

**Comment by Dtrieb** [comment]
On Version 1.23 now it works.
Thank you!
