### ISSUE TITLE
5G-NSA vs LTE in Display

### ISSUE THREAD

**Issue by christianrowlands** [christianrowlands/android-network-survey#39]
Bug reported by @pm4rcin

**Describe the bug**
Another thing that is not present is that the app doesn't show 5G-NSA but it only shows LTE on Data Network. It could be done because an app Privacy Cell can show it.

**Expected behavior**
The app should show 5G-NSA

**Additional context**
This issue was originally brought up in [this comment](https://github.com/christianrowlands/android-network-survey/issues/37#issuecomment-2056374394), but I moved it to its own issue.

**Comment by christianrowlands** [comment]
@pm4rcin I am not sure how to figure out if it is 5G-NSA or not. I am using the following Android API to get which data network is being used: https://developer.android.com/reference/android/telephony/TelephonyManager#getDataNetworkType()

Looking through all the possible return values at that link, I am not seeing one for 5G-NSA. I am guessing Privacy Cell is getting it from somewhere else, but I am not sure where. If you have any other thoughts I can try them out, but as of right now I don't see a way to get this information.

**Comment by pm4rcin** [comment]
Here you go, also you can even get if Carrier Aggregation is present. https://developer.android.com/reference/android/telephony/TelephonyDisplayInfo

**Comment by christianrowlands** [comment]
Oh, nice. I had not noticed that in the API docs before. Thanks for sending. I will get that added!

**Comment by pm4rcin** [comment]
> Oh, nice. I had not noticed that in the API docs before. Thanks for sending. I will get that added!

FYI I have just Asked Perplexity AI and since it has access to internet it showed good results. :)

**Comment by christianrowlands** [comment]
I was able to add the override network to the display. The only part left is to add an info box describing what the "Override Network" is.

<img width="482" alt="image" src="https://github.com/christianrowlands/android-network-survey/assets/8020686/bcc68a73-0b9b-4b17-9f7a-c36ff6d854c1">

**Comment by christianrowlands** [comment]
@pm4rcin , And here is the description

<img width="487" alt="image" src="https://github.com/christianrowlands/android-network-survey/assets/8020686/57604e70-af1a-481f-b543-173588aa405d">

Let me know if you have any suggestions for improving the layout or description.

**Comment by pm4rcin** [comment]
IMO it should be voice then data and then override layout because in other menus of android it's in this order. Also maybe use different color when override is present e.g. yellow or smth for font or even entire widget.

**Comment by christianrowlands** [comment]
Sorry for the slow response.

How about this @pm4rcin :

<img width="507" alt="image" src="https://github.com/christianrowlands/android-network-survey/assets/8020686/01d974f0-877b-4b5b-b772-7a686b27550b">

**Comment by pm4rcin** [comment]
No problem, we're not in hospital. ;) It looks great.
Offtop: Would you change the appid in the CI by e.g. appending `.beta` so if someone wants to test artifacts in the future there's no need to reinstall?

**Comment by christianrowlands** [comment]
Yeah, that would make it easier to allow both to be installed at the same time. I will look into that.
