### ISSUE TITLE
Update to the latest GPSTest code

### ISSUE THREAD

**Issue by christianrowlands** [christianrowlands/android-network-survey#40]
Suggestion from @pm4rcin

**Describe the request**
The GPS module looks like taken straight from the GPSTest but it's not fully up-to-date because it lacks SouthPAN (Australia / New Zealand) SBAS satellites.

**Additional context**
This issue was originally brought up in [this comment](https://github.com/christianrowlands/android-network-survey/issues/37#issuecomment-2056374394), but I moved it to its own issue.

**Comment by christianrowlands** [comment]
You are correct, I pull the source from the GPSTest app. I will pull in the latest code to get SouthPAN support in there, along with any other new features.

**Comment by pm4rcin** [comment]
I think it'd be good to give credits in README as a good practice.

**Comment by christianrowlands** [comment]
Good call. I added it here: https://github.com/christianrowlands/android-network-survey/tree/develop?tab=readme-ov-file#credits-and-acknowledgements

**Comment by pm4rcin** [comment]
It would be nice once you update the code to make it possible to change speed to kph because m/s is not convenient to parse. So either a setting or just change the default. Thanks!

**Comment by christianrowlands** [comment]
That makes sense. I will look into that.

**Comment by christianrowlands** [comment]
I updated to the latest GPSTest code and changed the speed to km/h. Here is the commit: https://github.com/christianrowlands/android-network-survey/commit/9f805bed8f4f17569765442284cee967e31251dd
