### ISSUE TITLE
don't ask for background location ob every start

### ISSUE THREAD

**Issue by woj-tek** [christianrowlands/android-network-survey#46]
**Is your feature request related to a problem? Please describe.**
Background location is optional an if user doesn't want / need ir then it shouldn't be nagged each time app is opened

**Comment by christianrowlands** [comment]
That is a great point. I actually did not even notice that since I just accept the permission the first time. I will get that fixed.

**Comment by christianrowlands** [comment]
@woj-tek , I fixed the problem so that you can prevent the dialog from opening each time. I will probably push out a release in a week or so.

**Comment by woj-tek** [comment]
Awesome! Thank you so much for quickly fixing it :-)
