### ISSUE TITLE
NS Server connection fails in Android 14

### ISSUE THREAD

**Issue by blaineam** [christianrowlands/android-network-survey#51]
**Describe the bug**
On android 14 Network Survey cannot establish a connection to a Network Survey Server. No errors reported the toggle switch just immediately flashes orange and back to red in a sub second. 

**To Reproduce**
1. Open Network Survey on an Android 14 device
2. Open the Network Survey Server Pane
3. Enter your Server's IP Address, Port and Device name
4. Toggle connection
5. See reported issue

**Expected behavior**
I expect the connection to be made like it does on an Android 11 device

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android Version: Android 14
 - Device: Samsung Galaxy A15 5G
 - Android Version: Android 14

**Additional context**
I even tried an old release v1.17 that had clearTextTraffic set to True just to be sure that wasn't the issue. 
All available permissions have been granted to the NS app
Using an old Android 11 device connects to same server without issue on same app version too.

**Comment by christianrowlands** [comment]
Thank you for reporting this issue.

What version of NS were you using when you tested on Android 14? This commit fixed a problem with the gRPC connection on Android 14: https://github.com/christianrowlands/android-network-survey/commit/b06a6fc6e0d0a8caa2aef767bed0f00bae4cc647

That commit was released in version 1.26.

However, it sounds like there is another issue, but I wanted to check the version number to be sure.

**Comment by blaineam** [comment]
I tried NS versions 1.27, 1.17, 1.28 and they all experienced the same issue on Android 14 across 2 different devices. 

Both NS 1.27 and 1.28 work fine to the same server with Android 11. 

Update: tested out NS 1.26 just to be sure and that one has the same behavior so not sure if there was a patch to Android 14 that broke the fix from that PR or not.

**Comment by christianrowlands** [comment]
I was able to find and fix the problem. It was an easy one for sure, sorry it took so long. I will push out a release in a few days, so keep an eye out for version 1.29.

Thanks again for reporting the bug!
