### ISSUE TITLE
Add application to main f-droid repo

### ISSUE THREAD

**Issue by pm4rcin** [christianrowlands/android-network-survey#52]
Hi, what do you think about adding application to the main fdroid repo? I think it would be beneficial because more people could discover it. On official client Izzy's repo is not turned on by default.

**Comment by christianrowlands** [comment]
I think that is a good idea. I looked into it a while back and remember it taking a bit of work to get an app into F-Droid. I will look again and see how much effort it will be.

**Comment by christianrowlands** [comment]
I submitted Network Survey to F-Droid, I am just waiting on them to approve and merge it. You can follow along here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15833

**Comment by pm4rcin** [comment]
Looks like it was merged. Thanks a lot! :)
