### ISSUE TITLE
UMTS: Show RNC and short cellid

### ISSUE THREAD

**Issue by Marhasp** [christianrowlands/android-network-survey#54]
Hello, would it be possible to display the RNC and the short cellid for UMTS?

Thank you

**Comment by christianrowlands** [comment]
Yep, I can certainly do that. I will code something up.

**Comment by christianrowlands** [comment]
Done: https://github.com/christianrowlands/android-network-survey/commit/f8e5a66d2d8c5c645e404adfbe3149ab84ec71a3

This change will show up in the next release. Thank you @Marhasp for the suggestion.
